# Generated by Django 4.1.5 on 2023-03-01 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('count', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('metal', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numizoomi.category')),
            ],
            options={
                'verbose_name_plural': 'Монеты',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='money_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numizoomi.money'),
        ),
    ]
