# Generated by Django 4.1.5 on 2023-04-23 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('numizoomi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='money',
            options={'ordering': ['-time_create', 'title'], 'verbose_name_plural': 'Монеты'},
        ),
        migrations.AddField(
            model_name='money',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='money',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='numizoomi.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='money',
            name='count',
            field=models.CharField(max_length=255, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='money',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Производства'),
        ),
        migrations.AlterField(
            model_name='money',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='money',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='money',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='money',
            name='metal',
            field=models.CharField(max_length=255, verbose_name='Металл'),
        ),
        migrations.AlterField(
            model_name='money',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='money',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='money',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='money',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='money',
            name='year',
            field=models.CharField(max_length=255, verbose_name='Год'),
        ),
    ]
